[node]
name = "helium-node"
rpc_bind = "0.0.0.0:20443"
seed = "0000000000000000000000000000000000000000000000000000000000000000"
working_dir = "/tmp/stacks-blockchain-data-01"

[burnchain]
chain = "bitcoin"
mode = "mocknet"
commit_anchor_block_within = 2500

[[mstx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 10000000000000000

[[mstx_balance]]
address = "ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y"
amount = 10000000000000000

[[mstx_balance]]
address = "ST1HB1T8WRNBYB0Y3T7WXZS38NKKPTBR3EG9EPJKR"
amount = 10000000000000000

[[mstx_balance]]
address = "STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP"
amount = 10000000000000000