[project]
name = 'storage-contracts'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.sBTC-DB]
path = 'contracts/sBTC-DB.clar'
clarity_version = 2
epoch = 2.4

[contracts.stacker-DB]
path = 'contracts/stacker-DB.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
