[alias]
stacks-node = "run --package stacks-node --"
fmt-stacks = "fmt -- --config group_imports=StdExternalCrate,imports_granularity=Module"
clippy-stacks = "clippy -p stx-genesis -p libstackerdb -p stacks-signer -p pox-locking -p clarity-types -p clarity -p libsigner -p stacks-common --no-deps --tests --all-features -- -D warnings"
clippy-stackslib = "clippy -p stackslib --no-deps -- -Aclippy::all -Wclippy::indexing_slicing -Wclippy::nonminimal_bool -Wclippy::clone_on_copy"

# Uncomment to improve performance slightly, at the cost of portability
#   * Note that native binaries may not run on CPUs that are different from the build machine
# [build]
# rustflags = ["-Ctarget-cpu=native"]

# Needed by perf to generate flamegraphs.
#[target.x86_64-unknown-linux-gnu]
#linker = "/usr/bin/clang"
#rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]

[patch."https://github.com/stacks-network/stacks-core.git"]
clarity = { path = "./clarity" }
stacks-common = { path = "./stacks-common" }

# Uncomment the patch below to use the local version of clarity-wasm
# [patch.'https://github.com/stacks-network/clarity-wasm.git']
# clar2wasm = { path = "../clarity-wasm/clar2wasm" }
