[package]
name = "pox-locking"
version = "2.4.0"
authors = [ "Jude Nelson <jude@stacks.org>",
            "Aaron Blankstein <aaron@blockstack.com>",
            "Ludo Galabru <ludovic@blockstack.com>" ]
license = "GPLv3"
homepage = "https://github.com/blockstack/stacks-blockchain"
repository = "https://github.com/blockstack/stacks-blockchain"
description = "Contract call result handler for applying PoX lock operations"
keywords = [ "stacks", "stx", "bitcoin", "crypto", "blockstack", "decentralized", "dapps", "blockchain" ]
readme = "README.md"
resolver = "2"
edition = "2021"
rust-version = "1.61"

[lib]
name = "pox_locking"
path = "src/lib.rs"

[dependencies]
clarity = { git = "https://github.com/stacks-network/stacks-core.git", rev = "eaa7c95f6f9e14615074d5b6a23c20a86c0a5e2b", default-features = false, optional = true }
stacks_common = { package = "stacks-common", git = "https://github.com/stacks-network/stacks-core.git", branch = "feat/clarity-wasm-next", default-features = false, optional = true  }
slog = { version = "2.5.2", features = [ "max_level_trace" ] }

[features]
default = ["stacks_common/default", "clarity/default"]
slog_json = ["stacks_common/slog_json", "clarity/slog_json"]
wasm = ["stacks_common/wasm", "clarity/wasm"]
