[network]
rpc_bind = "0.0.0.0:18443"
block_time = 7000
miner_address = "mx2uds6sgnn9znABQ6iDSSmXY9K5D4SHF9"
faucet_address = "n2pGfZaAVztWqFzuy8iLS3VSuHB2SimWUR"
bitcoind_rpc_host = "bitcoind:18443"
bitcoind_rpc_user = "admin"
bitcoind_rpc_pass = "admin"
genesis_timestamp = 1683539443
whitelisted_rpc_calls = [
    "listunspent",
    "importaddress",
    "sendrawtransaction",
    "getrawtransaction",
    "scantxoutset",
    "getrawmempool",
    "getblockhash",
]

[[blocks]]
count = 1
block_time = 20000
ignore_txs = false
