[node]
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
seed = "7cc9470ad14b9dbcbf8a3d589c8c21c82f5921df4e10759374426f286bf7299501"
local_peer_seed = "02d31e05c38053df17bcb023cb7f95a831f1208ff8234df3c8118a9729e2a6611e"
mock_miner = true
wait_time_for_microblocks = 0
#miner = true

[burnchain]
chain = "bitcoin"
mode = "mocknet"
peer_host = "bitcoind"
username = "admin"
password = "admin"
rpc_port = 18443
peer_port = 18444

[[ustx_balance]]
# "mnemonic": "point approve language letter cargo rough similar wrap focus edge polar task olympic tobacco cinnamon drop lawn boring sort trade senior screen tiger climb",
# "privateKey": "539e35c740079b79f931036651ad01f76d8fe1496dbd840ba9e62c7e7b355db001",
# "btcAddress": "n1htkoYKuLXzPbkn9avC2DJxt7X85qVNCK",
address = "ST3EQ88S02BXXD0T5ZVT3KW947CRMQ1C6DMQY8H19"
amount = 100000000000000

[[ustx_balance]]
# "mnemonic": "laugh capital express view pull vehicle cluster embark service clerk roast glance lumber glove purity project layer lyrics limb junior reduce apple method pear",
# "privateKey": "075754fb099a55e351fe87c68a73951836343865cd52c78ae4c0f6f48e234f3601",
# "btcAddress": "n2ZGZ7Zau2Ca8CLHGh11YRnLw93b4ufsDR",
address = "ST3KCNDSWZSFZCC6BE4VA9AXWXC9KEB16FBTRK36T"
amount = 100000000000000

[[ustx_balance]]
# "mnemonic": "level garlic bean design maximum inhale daring alert case worry gift frequent floor utility crowd twenty burger place time fashion slow produce column prepare",
# "privateKey": "374b6734eaff979818c5f1367331c685459b03b1a2053310906d1408dc928a0001",
# "btcAddress": "mhY4cbHAFoXNYvXdt82yobvVuvR6PHeghf",
address = "STB2BWB0K5XZGS3FXVTG3TKS46CQVV66NAK3YVN8"
amount = 100000000000000

[[ustx_balance]]
# "mnemonic": "drop guess similar uphold alarm remove fossil riot leaf badge lobster ability mesh parent lawn today student olympic model assault syrup end scorpion lab",
# "privateKey": "26f235698d02803955b7418842affbee600fc308936a7ca48bf5778d1ceef9df01",
# "btcAddress": "mkEDDqbELrKYGUmUbTAyQnmBAEz4V1MAro",
address = "STSTW15D618BSZQB85R058DS46THH86YQQY6XCB7"
amount = 100000000000000
