##
## Auto-opens a PR on the clarity-js-sdk repo to update the binary reference when a new release is published.
##

name: Open Clarity JS SDK PR

on:
  release:
    types:
      - released
  workflow_dispatch:

## Set some defaults for all jobs
defaults:
  run:
    shell: bash

## Set environment variables to be used in each step
env:
  CLARITY_JS_SDK_REPOSITORY: stacks-network/clarity-js-sdk
  COMMIT_USER: Hiro DevOps
  COMMIT_EMAIL: 45208873+blockstack-devops@users.noreply.github.com

jobs:
  run:
    name: Open Clarity JS SDK PR
    runs-on: ubuntu-latest
    # This condition can be removed once the main `stacks-blockchain` workflow creates pre-releases
    # when appropriate, instead of full releases for every tag passed in.
    if: "!contains(github.ref, '-rc')"
    steps:
      - name: Checkout latest clarity js sdk
        id: git_checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ env.CLARITY_JS_SDK_REPOSITORY }}
          ref: master

      - name: Determine Release Version
        id: get_release_version
        run: |
          RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/} | tr / -)
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Update SDK Tag
        id: update_sdk_tag
        run: sed -i "s@CORE_SDK_TAG = \".*\"@CORE_SDK_TAG = \"$RELEASE_VERSION\"@g" packages/clarity-native-bin/src/index.ts

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "chore: update clarity-native-bin tag"
          committer: ${{ env.COMMIT_USER }} <${{ env.COMMIT_EMAIL }}>
          author: ${{ env.COMMIT_USER }} <${{ env.COMMIT_EMAIL }}>
          branch: auto/update-bin-tag
          delete-branch: true
          title: "clarity-native-bin tag update: ${{ env.RELEASE_VERSION }}"
          labels: |
            dependencies
          body: |
            :robot: This is an automated pull request created from a new release in [stacks-blockchain](https://github.com/stacks-network/stacks-blockchain/releases).

            Updates the clarity-native-bin tag.
          assignees: zone117x
          reviewers: zone117x
