## Perform Clippy checks - currently set to defaults
##   https://github.com/rust-lang/rust-clippy#usage
##   https://rust-lang.github.io/rust-clippy/master/index.html
##
name: Clippy Checks

# Only run when:
#   - PRs are (re)opened against develop branch
on:
  merge_group:
    types:
      - checks_requested
  pull_request:
    branches:
      - develop
      - aac-client-breaking # temp branch for aac work
    types:
      - opened
      - reopened
      - synchronize

jobs:
  clippy_check:
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Define Rust Toolchain
        id: define_rust_toolchain
        run: echo "RUST_TOOLCHAIN=$(cat ./rust-toolchain)" >> $GITHUB_ENV

      - name: Setup Rust Toolchain
        id: setup_rust_toolchain
        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy
          cache: false

      - name: Clippy
        id: clippy
        run: cargo clippy-stacks

      - name: Clippy Stackslib
        id: clippy-stackslib
        run: cargo clippy-stackslib
