name: Tracking PR Mutants

on:
  pull_request:

jobs:
  # Mutants testing: Execute on PR on packages that have functions modified, and fail the workflow if there are missed or timeout mutations
  incremental-mutants:
    name: Incremental Mutants Testing

    runs-on: ubuntu-latest

    steps:
      - name: Run filtering pr mutants from actions
        uses: ASuciuX/actions/mutation-testing/filter-pr@feat/mutation-testing
