name: Build Alpine Binary Image

env:
  REPO_OWNER: wileyj

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
        description: "semver tag for alpine images"
      docker_platforms:
        required: true
        description: "Arch to buid alpine images"
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  image:
    if: ${{ inputs.tag != '' }}
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@v3
      - name: Set Vars
        id: set_vars
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "GITHUB_REF_SHORT=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        id: docker_qemu
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: docker_buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Metadata
        id: docker_metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REPO_OWNER }}/${{ github.event.repository.name }}
          tags: |
            type=raw,value=latest,enable=${{ inputs.tag != '' && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) )}}
            type=raw,value=${{ inputs.tag }},enable=${{ inputs.tag != '' }}
            type=ref,enable=true,priority=600,event=tag
            type=ref,event=branch
            type=ref,event=pr
      - name: Login to DockerHub
        id: docker_login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          file: ./.github/actions/dockerhub/Dockerfile.alpine-binary
          platforms: ${{ inputs.docker_platforms }}
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          build-args: |
            TAG=${{ inputs.tag}}
            STACKS_NODE_VERSION=${{ inputs.tag || env.GITHUB_SHA_SHORT }}
            GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}
            GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}
            BUILDKIT_PROGRESS=plain
          push: true
