## Github workflow to run full genesis and unit tests
## Runs when:
##   - 'CI' workflow is triggered for a PR (open, synchronize, approval)
##   - 'CI' workfow is triggered manually (with or without an input tag)

name: Tests::Stacks Blockchain

on:
  workflow_call:

## Set some defaults for all jobs
defaults:
  run:
    shell: bash

## Set environment variables to be used in each step
env:
  BITCOIND_TEST: 1
  RUST_BACKTRACE: full
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 15

## Concurrency: only cancel an in progress workflow if this is for a PR
concurrency:
  group: stacks-blockchain-tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ## Full genesis test with code coverage
  full-genesis:
    name: Full Genesis Test
    runs-on: ubuntu-latest
    ## Run a maximum of 2 concurrent tests from the test matrix
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        test-name:
          - neon_integrations::bitcoind_integration_test
    steps:
      ## Checkout the code
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      ## Install rust toolchain (llvm-tools-preview)
      - name: Setup Rust Toolchain
        id: setup_rust_toolchain
        uses: actions-rust-lang/setup-rust-toolchain@f3c84ee10bf5a86e7a5d607d487bf17d57670965 # v1.5.0
        with:
          toolchain: stable
          components: llvm-tools-preview
          cache: false

      ## Restore cargo cache data
      - name: Restore Cargo Cache
        id: restore_cargo_cache
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          fail-on-cache-miss: true
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ github.event.repository.name }}-${{ github.sha }}-cargo

      ## Restore bitcoin cache data
      - name: Restore Bitcoin Binary Cache
        id: restore_bitcoin_cache
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          fail-on-cache-miss: true
          path: /tmp/bitcoin
          key: ${{ github.event.repository.name }}-bitcoin-binaries

      ## Restore genesis nextest archive cache data
      - name: Restore Genesis Archive Cache
        id: restore_test-archive_cache
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          fail-on-cache-miss: true
          path: /tmp/genesis_archive.tar.zst
          key: ${{ github.event.repository.name }}-${{ github.sha }}-genesis-archive

      ## Restore nextest target cache data
      - name: Restore Target Cache
        id: restore_target_cache
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          fail-on-cache-miss: true
          path: ./target
          key: ${{ github.event.repository.name }}-${{ github.sha }}-target

      ## Symlink bitoind to $PATH
      - name: Link Bitcoin Binary
        id: bitcoin_binary
        run: |
          sudo ln -s /tmp/bitcoin/bin/bitcoind /bin/
          ls -al /bin/bitcoind

      ## Run test matrix using cached archive file
      - name: Run Tests
        id: run_tests
        run: |
          cargo nextest run \
            --test-threads 1 \
            --run-ignored all \
            --retries 2 \
            --final-status-level fail \
            --archive-file /tmp/genesis_archive.tar.zst \
            "${{ matrix.test-name }}"

      ## Generate code coverage using grcov
      - name: Run grcov
        id: run_grcov
        run: |
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
          echo "created=true\n" >> $GITHUB_OUTPUT

      ## Upload coverage to codecov
      ##   - retry on a failed upload 3x using 'Wandalen/wretry.action'
      - name: Upload Code Coverage
        id: code_coverage
        uses: Wandalen/wretry.action@a163f62ae554a8f3cbe27b23db15b60c0ae2e93c # v1.3.0
        with:
          action: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
          with: |
            files: ./lcov.info
            name: large_genesis
            fail_ci_if_error: false
            verbose: true
          attempt_limit: 3
          attempt_delay: 10000

  ## Unit tests with code coverage
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    ## Partition the tests in 8 shards
    strategy:
      matrix:
        partition: [1, 2, 3, 4, 5, 6, 7, 8] # partition the tests into 8 jobs
    steps:
      ## Checkout the code
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      ## install rust toolchain
      - name: Setup Rust Toolchain
        id: setup_rust_toolchain
        uses: actions-rust-lang/setup-rust-toolchain@f3c84ee10bf5a86e7a5d607d487bf17d57670965 # v1.5.0
        with:
          toolchain: stable
          components: llvm-tools-preview
          cache: false

      ## Restore cargo cache data
      - name: Restore Cargo Cache
        id: restore_cargo_cache
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          fail-on-cache-miss: true
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ github.event.repository.name }}-${{ github.sha }}-cargo

      ## Restore bitcoin cache data
      - name: Restore Bitcoin Binary Cache
        id: restore_bitcoin_cache
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          fail-on-cache-miss: true
          path: /tmp/bitcoin
          key: ${{ github.event.repository.name }}-bitcoin-binaries

      ## Restore test archive cache data
      - name: Restore Test Archive Cache
        id: restore_test-archive_cache
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          fail-on-cache-miss: true
          path: /tmp/test_archive.tar.zst
          key: ${{ github.event.repository.name }}-${{ github.sha }}-test-archive

      ## Restore target cache data
      - name: Restore Target Cache
        id: restore_target_cache
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          fail-on-cache-miss: true
          path: ./target
          key: ${{ github.event.repository.name }}-${{ github.sha }}-target

      ## Symlink bitoind to $PATH
      - name: Link Bitcoin Binary
        id: bitcoin_binary
        run: |
          sudo ln -s /tmp/bitcoin/bin/bitcoind /bin/
          ls -al /bin/bitcoind

      ## Run test shards using cached archive file (defined as matrix.partition)
      ##   - timeout after 30 minutes
      - name: Run Tests
        id: run_tests
        timeout-minutes: 30
        run: |
          cargo nextest run \
            --test-threads num-cpus \
            --retries 2 \
            --final-status-level fail \
            --fail-fast \
            --archive-file /tmp/test_archive.tar.zst \
            --partition count:${{ matrix.partition }}/8

      ## Generate code coverage using grcov
      - name: Run grcov
        if: inputs.tag != ''
        id: run_grcov
        run: |
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
          echo "created=true\n" >> $GITHUB_OUTPUT

      ## Upload coverage to codecov
      ##   - retry on a failed upload 3x using 'Wandalen/wretry.action'
      - name: Upload Code Coverage
        id: code_coverage
        uses: Wandalen/wretry.action@a163f62ae554a8f3cbe27b23db15b60c0ae2e93c # v1.3.0
        with:
          action: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
          with: |
            files: ./lcov.info
            name: unit_tests
            fail_ci_if_error: false
            verbose: true
          attempt_limit: 3
          attempt_delay: 10000

  ## Create HTML-ized openapi doc
  open-api-validation:
    name: OpenAPI Validation
    runs-on: ubuntu-latest
    steps:
      ## Checkout the code
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      ## Use redoc to generate HTML of openapi.yml
      - name: Redoc
        id: run_redoc
        uses: seeebiii/redoc-cli-github-action@c9649b33918da5eb290b81cd03a943caea091540 # v10
        with:
          args: "bundle -o ./open-api-docs.html ./docs/rpc/openapi.yaml"

      ## Test the resultant html
      - name: check result
        id: check_redoc
        run: |
          test -f ./open-api-docs.html || (echo "Missing ./open-api-docs.html from previous step." && exit 1)

      ## Upload the html file artifact
      - name: Upload bundled html
        id: upload_html_artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: open-api-bundle
          path: |
            ./open-api-docs.html

  ## Disabled
  ##   - this test currently takes several hours to run
  nettest:
    if: ${{ false }}
    name: Net-Test
    runs-on: ubuntu-latest
    steps:
      ## Checkout the code
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Run network relay tests
        id: nettest
        env:
          DOCKER_BUILDKIT: 1
        run: docker build -f ./.github/actions/bitcoin-int-tests/Dockerfile.net-tests .

  ## Core contract tests
  core-contracts-clarinet-test:
    name: Core Contracts Test
    runs-on: ubuntu-latest
    steps:
      ## Checkout the code
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      ## Use Clarinet to run contract unit-tests
      - name: Execute core contract unit tests in Clarinet
        id: clarinet_unit_test
        uses: docker://hirosystems/clarinet:latest
        with:
          args: test --coverage --manifest-path=./contrib/core-contract-tests/Clarinet.toml

      ## Upload coverage to codecov
      ##   - retry on a failed upload 3x using 'Wandalen/wretry.action'
      - name: Upload Code Coverage
        id: code_coverage
        uses: Wandalen/wretry.action@a163f62ae554a8f3cbe27b23db15b60c0ae2e93c # v1.3.0
        with:
          action: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
          with: |
            files: ./coverage.lcov
            fail_ci_if_error: false
            verbose: true
          attempt_limit: 3
          attempt_delay: 10000
